name: 'Install GTK'
author: 'Sebastian Pape'
description: 'This will add GVSBuild to the path on Windows and install the requested packages GTK on MacOS and Linux. Uses caching for GVSBuild download.'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  windows-release:
    description: 'Release Tag. Either "latest" or e.g. "tags/2025.4.0"'
    required: true
    default: 'latest'
  windows-gtk-version:
    description: 'Wildcard used to match filenames, but can be used to switch to eg. GTK3'
    required: true
    default: 'GTK4*.zip'
  linux-release:
    description: 'APT-Package Name for Ubuntu'
    required: true
    default: 'libgtk-4-dev'
  macos-release:
    description: 'Homebrew-Package Name for MacOS'
    required: true
    default: 'gtk4'
  
runs:
  using: "composite"
  steps:
    - name: 'Install Package in Linux'
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt update && sudo apt install -y ${{ inputs.linux-release }}
    - name: 'Install Package in MacOS'
      if: runner.os == 'macOS'
      shell: bash
      run: brew install ${{ inputs.macos-release }}
    - name: 'Determine Windows Release'
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        (Invoke-RestMethod -Uri https://api.github.com/repos/wingtk/gvsbuild/releases/${{ inputs.windows-release }} -ContentType "application/json").assets | foreach {
        	if( $_.name -like "${{ inputs.windows-gtk-version }}" ){
             echo "WINDOWS_GVS_DOWNLOAD=$($_.browser_download_url)" >> $Env:GITHUB_ENV
             exit 0
          }
        }
        exit 1
    - name: Cache GVSBuild
      id: cache-gvs
      uses: actions/cache@v4
      if: runner.os == 'Windows'
      with:
        key: ${{ env.WINDOWS_GVS_DOWNLOAD }}
        path: C:/gtk
    - name: 'Download, Extract and Add to Path Windows'
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        if( ${{ steps.cache-gvs.outputs.cache-hit != 'true' }} ){
        	Invoke-WebRequest -OutFile gtk.zip ${{env.WINDOWS_GVS_DOWNLOAD}}
          (Expand-Archive -Path gtk.zip -DestinationPath "C:\gtk") -and (rm .\gtk.zip)
        }
        echo "C:\gtk\bin;" >> $Env:GITHUB_PATH
