name: Test for all platforms
on:
  push:
  pull_request:
  workflow_dispatch: 

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout the actions file
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Add GTK to Runner
        uses: ./
